test_that("Test get codes with multiple desc", {
  df_test <- tibble::tribble(
    ~start_date, ~end_date, ~snomed_code, ~description, ~active_at_start, ~active_at_start, ~active_at_end,
    "2023-08-01", "2024-07-31", "100", "One code one description", 100, TRUE, TRUE,
    "2022-08-01", "2023-07-31", "100", "One code one description", 100, TRUE, TRUE,
    "2023-08-01", "2024-07-31", "200", " One code two description", 200, TRUE, TRUE,
    "2022-08-01", "2023-07-31", "200", " One code two descriptions", 200, TRUE, TRUE
  )

  expect_equal(get_codes_with_multiple_desc(df_test), c("200"))
})

test_that("Test get codes with encoding problem", {
  df_test <- tibble::tribble(
    ~start_date, ~end_date, ~snomed_code, ~description, ~active_at_start, ~active_at_start, ~active_at_end,
    "2023-08-01", "2024-07-31", "100", "No encoding problems", 100, TRUE, TRUE,
    "2022-08-01", "2023-07-31", "200", " Encoding problems Ã", 200, TRUE, TRUE,
    "2022-08-01", "2023-07-31", "300", " Encoding problems â", 300, TRUE, TRUE
  )

  expect_equal(get_codes_with_encoding_problems(df_test), c("200", "300"))
})

test_that("Test fix a circumflex lowercase encoding", {
  a_circumflex_lower <- c(
    "Provision of information about Infant crying is normal, Comforting methods can help, Itâ€™s OK to walk away, Never, ever shake a baby (procedure)",
    "Breast implantâ€“associated anaplastic large-cell lymphoma (disorder)",
    "Vitamin Bâ,\u0081â,, deficiency anaemia due to intrinsic factor deficiency",
    "Vitamin Bâ,\u0081â,, deficiency anaemia due to selective vitamin Bâ,\u0081â,, malabsorption with proteinuria",
    "Other dietary vitamin Bâ,\u0081â,, deficiency anaemia",
    "Other vitamin Bâ,\u0081â,, deficiency anaemias",
    "Vitamin Bâ,\u0081â,, deficiency anaemia, unspecified",
    "Megavitamin-Bâ,† syndrome",
    "GMâ,, gangliosidosis",
    "Poisoning: Histamine Hâ,,-receptor antagonists",
    "Vitamin Bâ,\u0081â,,, folic acid and other anti-megaloblastic-anaemia preparations",
    "Histamine Hâ,,-receptor antagonists"
  )

  expected_a_circumflex_lower_fix <- c(
    "Provision of information about Infant crying is normal, Comforting methods can help, It's OK to walk away, Never, ever shake a baby (procedure)",
    "Breast implant-associated anaplastic large-cell lymphoma (disorder)",
    "Vitamin B12 deficiency anaemia due to intrinsic factor deficiency",
    "Vitamin B12 deficiency anaemia due to selective vitamin B12 malabsorption with proteinuria",
    "Other dietary vitamin B12 deficiency anaemia",
    "Other vitamin B12 deficiency anaemias",
    "Vitamin B12 deficiency anaemia, unspecified",
    "Megavitamin-B6 syndrome",
    "GM2 gangliosidosis",
    "Poisoning: Histamine H2-receptor antagonists",
    "Vitamin B12, folic acid and other anti-megaloblastic-anaemia preparations",
    "Histamine H2-receptor antagonists"
  )

  expect_equal(fix_encoding(a_circumflex_lower), expected_a_circumflex_lower_fix)
})

# test_that("Test fix a tilde uppercase encoding", {

# a_tilde_upper <- c(
#   "Serum SjÃ¶gren's syndrome A 60 kiloDalton antibody (Ro) concentration (observable entity)",
#   "Serum SjÃ¶gren's syndrome A 52 kiloDalton antibody (Ro) concentration (observable entity)",
#   "SjÃ¶gren-Larsson syndrome (disorder)",
#   "ChÃ©diak-Higashi syndrome (disorder)",
#   "DÃ©jÃ©rine-Sottas disease (disorder)",
#   "SÃ©zary's disease (disorder)",
#   "MÃ©niÃ¨re's disease (disorder)",
#   "SÃ©zary's disease of lymph nodes of multiple sites (disorder)",
#   "WaldenstrÃ¶m macroglobulinemia (disorder)",
#   "Henoch-SchÃ¶nlein purpura (disorder)",
#   "Myopathy due to SjÃ¶gren's disease (disorder)",
#   "Keratoconjunctivitis sicca (excluding SjÃ¶gren syndrome) (disorder)",
#   "Active cochleovestibular MÃ©niÃ¨re's disease (disorder)",
#   "Active cochlear MÃ©niÃ¨re's disease (disorder)",
#   "Active vestibular MÃ©niÃ¨re's disease (disorder)",
#   "Inactive MÃ©niÃ¨re's disease (disorder)",
#   "Lung disease with SjÃ¶gren's disease (disorder)",
#   "CafÃ© au lait spot (disorder)",
#   "DÃ©jÃ  pensÃ© (finding)",
#   "Cochlear MÃ©niÃ¨re syndrome (disorder)",
#   "Vestibular MÃ©niÃ¨re syndrome (disorder)",
#   "Henoch-SchÃ¶nlein nephritis (disorder)",
#   "KÃ¶bner psoriasis (disorder)",
#   "Primary SjÃ¶gren's syndrome (disorder)",
#   "Primary SjÃ¶gren's syndrome with organ/system involvement (disorder)",
#   "Primary SjÃ¶gren's syndrome with multisystem involvement (disorder)",
#   "Secondary SjÃ¶gren's syndrome (disorder)",
#   "Secondary SjÃ¶gren's syndrome with organ/system involvement (disorder)",
#   "Secondary SjÃ¶gren's syndrome with multisystem involvement (disorder)",
#   "Postinfective Henoch-SchÃ¶nlein purpura (disorder)",
#   "KÃ¼mmell disease (disorder)",
#   "SÃ©zary disease of skin (disorder)",
#   "History of vertigo or MÃ©niÃ¨re's disease (situation)",
#   "LasÃ¨gue sign (finding)",
#   "History of MÃ©niÃ¨re's disease (situation)",
#   "Brown-SÃ©quard syndrome (disorder)",
#   "Pidgin and CrÃ©ole language (qualifier value)",
#   "French CrÃ©ole language (qualifier value)",
#   "LasÃ¨gue test response (observable entity)",
#   "LasÃ¨gue test positive (finding)",
#   "LasÃ¨gue test negative (finding)",
#   "DÃ©jÃ  vu (finding)",
#   "CrÃ©ole language (qualifier value)",
#   "Hand-SchÃ¼ller-Christian disease (disorder)",
#   "Chondrodysplasia punctata, Conradi-HÃ¼nermann type (disorder)",
#   "Papillon-LefÃ¨vre syndrome (disorder)",
#   "Anogenital verrucous carcinoma of Buschke-LÃ¶wenstein (disorder)",
#   "Vulval verrucous carcinoma of Buschke-LÃ¶wenstein (disorder)",
#   "Multiple cafÃ©-au-lait macules due to neurofibromatosis (disorder)",
#   "TorrÃ©-Muir syndrome (disorder)",
#   "Main spoken language French CrÃ©ole (finding)",
#   "Guillain-BarrÃ© syndrome (disorder)",
#   "BoutonniÃ¨re deformity (disorder)",
#   "Education about emptying bladder using CredÃ© maneuver (procedure)",
#   "Montgomery-Ã…sberg depression rating scale (assessment scale)",
#   "Roussy-LÃ©vy syndrome (disorder)",
#   "Abscess of LittrÃ©'s glands (disorder)",
#   "SÃ©zary's disease (morphologic abnormality)",
#   "Iodamoeba bÃ¼tschlii (organism)",
#   "BouffÃ©e dÃ©lirante (disorder)",
#   "LÃ¶ffler's syndrome (disorder)",
#   "Acute motor sensory axonal Guillain-BarrÃ© syndrome (disorder)",
#   "Iris bombÃ© (disorder)",
#   "Keratoconjunctivitis sicca, in SjÃ¶gren's syndrome (disorder)",
#   "Marinesco-SjÃ¶gren syndrome (disorder)",
#   "Klumpke-DÃ©jerine paralysis (disorder)",
#   "SjÃ¶gren's syndrome (disorder)",
#   "Pelger-HuÃ«t anomaly (disorder)",
#   "Born in Ã…land Islands (finding)",
#   "Born in RÃ©union (finding)",
#   "Born in CuraÃ§ao (finding)",
#   "SÃ©zary's disease of spleen (disorder)",
#   "Main spoken language Norwegian BokmÃ¥l (finding)",
#   "Main spoken language VolapÃ¼k (finding)",
#   "SÃ©zary disease",
#   "WaldenstrÃ¶m macroglobulinaemia",
#   "Concentric sclerosis [BalÃ³]",
#   "Guillain-BarrÃ© syndrome",
#   "MÃ©niÃ¨re disease",
#   "AcnÃ© excoriÃ©e",
#   "CafÃ© au lait spots",
#   "Sicca syndrome [SjÃ¶gren]",
#   "BehÃ§et disease",
#   "Juvenile osteochondrosis of head of femur [Legg-CalvÃ©-Perthes]",
#   "KienbÃ¶ck disease of adults"
# )

# expected_a_tilde_upper_fix <- c(
#   "Serum SjÃ¶gren's syndrome A 60 kiloDalton antibody (Ro) concentration (observable entity)",
#   "Serum SjÃ¶gren's syndrome A 52 kiloDalton antibody (Ro) concentration (observable entity)",
#   "SjÃ¶gren-Larsson syndrome (disorder)",
#   "ChÃ©diak-Higashi syndrome (disorder)",
#   "DÃ©jÃ©rine-Sottas disease (disorder)",
#   "SÃ©zary's disease (disorder)",
#   "MÃ©niÃ¨re's disease (disorder)",
#   "SÃ©zary's disease of lymph nodes of multiple sites (disorder)",
#   "WaldenstrÃ¶m macroglobulinemia (disorder)",
#   "Henoch-SchÃ¶nlein purpura (disorder)",
#   "Myopathy due to SjÃ¶gren's disease (disorder)",
#   "Keratoconjunctivitis sicca (excluding SjÃ¶gren syndrome) (disorder)",
#   "Active cochleovestibular MÃ©niÃ¨re's disease (disorder)",
#   "Active cochlear MÃ©niÃ¨re's disease (disorder)",
#   "Active vestibular MÃ©niÃ¨re's disease (disorder)",
#   "Inactive MÃ©niÃ¨re's disease (disorder)",
#   "Lung disease with SjÃ¶gren's disease (disorder)",
#   "CafÃ© au lait spot (disorder)",
#   "DÃ©jÃ  pensÃ© (finding)",
#   "Cochlear MÃ©niÃ¨re syndrome (disorder)",
#   "Vestibular MÃ©niÃ¨re syndrome (disorder)",
#   "Henoch-SchÃ¶nlein nephritis (disorder)",
#   "KÃ¶bner psoriasis (disorder)",
#   "Primary SjÃ¶gren's syndrome (disorder)",
#   "Primary SjÃ¶gren's syndrome with organ/system involvement (disorder)",
#   "Primary SjÃ¶gren's syndrome with multisystem involvement (disorder)",
#   "Secondary SjÃ¶gren's syndrome (disorder)",
#   "Secondary SjÃ¶gren's syndrome with organ/system involvement (disorder)",
#   "Secondary SjÃ¶gren's syndrome with multisystem involvement (disorder)",
#   "Postinfective Henoch-SchÃ¶nlein purpura (disorder)",
#   "KÃ¼mmell disease (disorder)",
#   "SÃ©zary disease of skin (disorder)",
#   "History of vertigo or MÃ©niÃ¨re's disease (situation)",
#   "LasÃ¨gue sign (finding)",
#   "History of MÃ©niÃ¨re's disease (situation)",
#   "Brown-SÃ©quard syndrome (disorder)",
#   "Pidgin and CrÃ©ole language (qualifier value)",
#   "French CrÃ©ole language (qualifier value)",
#   "LasÃ¨gue test response (observable entity)",
#   "LasÃ¨gue test positive (finding)",
#   "LasÃ¨gue test negative (finding)",
#   "DÃ©jÃ  vu (finding)",
#   "CrÃ©ole language (qualifier value)",
#   "Hand-SchÃ¼ller-Christian disease (disorder)",
#   "Chondrodysplasia punctata, Conradi-HÃ¼nermann type (disorder)",
#   "Papillon-LefÃ¨vre syndrome (disorder)",
#   "Anogenital verrucous carcinoma of Buschke-LÃ¶wenstein (disorder)",
#   "Vulval verrucous carcinoma of Buschke-LÃ¶wenstein (disorder)",
#   "Multiple cafÃ©-au-lait macules due to neurofibromatosis (disorder)",
#   "TorrÃ©-Muir syndrome (disorder)",
#   "Main spoken language French CrÃ©ole (finding)",
#   "Guillain-BarrÃ© syndrome (disorder)",
#   "BoutonniÃ¨re deformity (disorder)",
#   "Education about emptying bladder using CredÃ© maneuver (procedure)",
#   "Montgomery-Ã…sberg depression rating scale (assessment scale)",
#   "Roussy-LÃ©vy syndrome (disorder)",
#   "Abscess of LittrÃ©'s glands (disorder)",
#   "SÃ©zary's disease (morphologic abnormality)",
#   "Iodamoeba bÃ¼tschlii (organism)",
#   "BouffÃ©e dÃ©lirante (disorder)",
#   "LÃ¶ffler's syndrome (disorder)",
#   "Acute motor sensory axonal Guillain-BarrÃ© syndrome (disorder)",
#   "Iris bombÃ© (disorder)",
#   "Keratoconjunctivitis sicca, in SjÃ¶gren's syndrome (disorder)",
#   "Marinesco-SjÃ¶gren syndrome (disorder)",
#   "Klumpke-DÃ©jerine paralysis (disorder)",
#   "SjÃ¶gren's syndrome (disorder)",
#   "Pelger-HuÃ«t anomaly (disorder)",
#   "Born in Ã…land Islands (finding)",
#   "Born in RÃ©union (finding)",
#   "Born in CuraÃ§ao (finding)",
#   "SÃ©zary's disease of spleen (disorder)",
#   "Main spoken language Norwegian BokmÃ¥l (finding)",
#   "Main spoken language VolapÃ¼k (finding)",
#   "SÃ©zary disease",
#   "WaldenstrÃ¶m macroglobulinaemia",
#   "Concentric sclerosis [BalÃ³]",
#   "Guillain-BarrÃ© syndrome",
#   "MÃ©niÃ¨re disease",
#   "AcnÃ© excoriÃ©e",
#   "CafÃ© au lait spots",
#   "Sicca syndrome [SjÃ¶gren]",
#   "BehÃ§et disease",
#   "Juvenile osteochondrosis of head of femur [Legg-CalvÃ©-Perthes]",
#   "KienbÃ¶ck disease of adults"
# )

#   expect_equal(fix_encoding(a_tilde_upper), expected_a_tilde_upper_fix)
# })
