# This file tells the R package where to download each ready-to-use dataset
# The download link for a release is always:
# https://github.com/bennettoxford/opencodecounts/releases/download/{tag}/{dataset}.parquet
# where {tag} is {dataset name with dashes instead of underscores}-v{version},
# e.g. version 0.1.0 of snomed_usage has the tag "snomed-usage-v0.1.0".

datasets:
  snomed_usage:
    versions:
      - version: "0.1.0"
        url: "https://github.com/bennettoxford/opencodecounts/releases/download/snomed-usage-v0.1.0/snomed_usage.parquet"
  icd10_usage:
    versions:
      - version: "0.1.0"
        url: "https://github.com/bennettoxford/opencodecounts/releases/download/icd10-usage-v0.1.0/icd10_usage.parquet"
  icd10_usage_breakdowns:
    versions:
      - version: "0.1.0"
        url: "https://github.com/bennettoxford/opencodecounts/releases/download/icd10-usage-breakdowns-v0.1.0/icd10_usage_breakdowns.parquet"
  opcs4_usage:
    versions:
      - version: "0.1.0"
        url: "https://github.com/bennettoxford/opencodecounts/releases/download/opcs4-usage-v0.1.0/opcs4_usage.parquet"
  opcs4_usage_breakdowns:
    versions:
      - version: "0.1.0"
        url: "https://github.com/bennettoxford/opencodecounts/releases/download/opcs4-usage-breakdowns-v0.1.0/opcs4_usage_breakdowns.parquet"
